Add `JsExport` to application service requests
This didn't work before due to a compilation error: https://youtrack.jetbrains.com/issue/KT-57356

But, by removing `@JsExport` from `ApplicationService`, where it isn't really needed, compilation succeeds. As part of this, old TypeScript unit tests operating on request objects were reintroduced.

This again changed the JS export drastically enough so that the custom typescript declarations hacking into non-exported JS exports had to be updated.